import Head from "next/head";
import { Inter } from "@next/font/google";
import { signOut } from "next-auth/react";
import { GetServerSideProps } from "next";
import { authOptions } from "pages/api/auth/[...nextauth]";
import { getServerSession, Session } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

interface HomePageProps {
  session: Session;
}

export default function Home({ session }: HomePageProps) {
  return (
    <>
      <Head>
        <title>Exam</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button onClick={() => signOut()}>Sign Out</button>
        <h1>Dashboard</h1>
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getServerSession(context.req, context.res, authOptions);

  if (!session) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }

  return {
    props: {
      session,
    },
  };
};
