import Head from "next/head";
import { signOut } from "next-auth/react";
import { GetServerSideProps } from "next";
import { authOptions } from "pages/api/auth/[...nextauth]";
import { getServerSession } from "next-auth";
import Layout from "../components/Layout/Layout";
import ExamSubscriber from "@/components/ExamSubscriber/ExamSubscriber";
interface HomePageProps {
  usersession: UserSession;
}

const Home = ({ usersession }: HomePageProps) => {
  return (
    <>
      <Head>
        <title>Exam</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout usersession={usersession}>
        <div onClick={() => signOut()}>Sign Out</div>
        <h1>Welcome {usersession.user.neptun} </h1>
        <h2>You are a {usersession.user.role}</h2>
        <hr></hr>
        <ExamSubscriber />
      </Layout>
    </>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const usersession = await getServerSession(
    context.req,
    context.res,
    authOptions
  );

  if (!usersession) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }

  return {
    props: {
      usersession,
    },
  };
};
